[MD-20] Conversation Feature
2110366-2566-2/MonDooDuang pull request #11
Opened 2024-02-10 03:06 UTC by IamKittitat

- Install and use socket.io
- Backend For conversation  (Include createConversation that is not used here)
- Frontend For conversation 
- Rename files, folders, route from chat -> conversation 

**NOTED: The feature still uses mock data, after the Auth Feature is merged we might need more PR to fix this.**

2024-02-10 16:34 UTC, IamMrTeapot requested changes

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/models/conversation/conversation.model.ts
> +}
ทำไมบางอันใช้ camelCase บางอันใช้ snake_case นะ?

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/repositories/conversation.repository.ts
> +          SELECT conversationid, created_at
เอาล่ะ ไม่ได้อ่าน sql ละเอียด ทำไม naming มันนัวแบบนี้นะ

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/models/conversation/conversation.model.ts
> +}
แล้วสร้างมาไม่เห็นได้เรียกใช้สักที่เลยพี่

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/models/conversation/conversation.model.ts
> +}
ถ้าเรียกใช้แล้ว sql เป็น conversationid แต่ typescript เป็น conversationId มันจะไม่เข้าด้วยนะ

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/repositories/conversation.repository.ts
> +      return { isSuccess: false, data: null }
false ไปแล้วไม่ต้อง return data: null ก็ได้ frontend รู้

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/services/conversation/conversation.services.ts
> +    data.lastMessage = data.lastMessage === null ? "" : data.lastMessage
data.lastMessage = data.lastMessage ?? ""

2024-02-10 16:34 UTC, IamMrTeapot commented on backend/src/services/conversation/conversation.services.ts
> +    let prevTimeSent: number = 0
อันนี้บอกเฉย ๆ ไม่ต้องแก้อะไร เห็นประกาศ type หลายที่ จะบอกว่าพวก type default แบบนี้มัน auto detect อยู่แล้ว ไม่ประกาศก็ได้

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/common/services/serviceConfig.ts
> +}
ย้ายไปใช้ environment.ts แล้ว ลบทิ้งด้วย

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/ConversationPage.tsx
> +const mockIsSystemReport = true
หน้านี้ไม่ใช่ system report อยู่แล้ว ยัด true ไปใน modal ได้เลย

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/ConversationPage.tsx
> +  const [conversationIds, setConversationIds] = useState<string[]>([""])
default ควรเป็น empty array?

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/services/ConversationService.ts
ย้ายไปใช้ environment.ts

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/services/ConversationService.ts
fetch มาแล้วต้อง response.json() ด้วย ไม่งั้นมีโอกาสพัง

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/services/ConversationService.ts
ลองไปดูใน StripeService ก็ได้

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/ConversationPage.tsx
> +      const conversationIds = await response.json()
ย้าย response.json ไป service ดีกว่า เวลาจะ handle response error หรือจะปรับแต่ง response ก่อนใช้ จะได้แก้ที่ service ไฟล์เดียว

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/ConversationPage.tsx
> +      setSelectedConversationId(conversationIds[0])
ไม่ได้ handle case empty array

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/ConversationPage.tsx
> +  const [selectedConversationId, setSelectedConversationId] = useState<string>("")
ใช้ useState<string | null>(null) ดีกว่า จะได้แยกออกว่า id invalid หรือ ไม่มี selected conversation

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationBox.tsx
> +const socket = io(serviceConfig.backendBaseUrl)
ย้ายไปใช้ environment.ts

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationBox.tsx
> +      if (conversationId) {
คนที่ handle ปัญหานี้น่าจะเป็น parent component ที่จะส่ง conversationId มาให้นะ ถ้าแก้ initial value ของ conversationIds เป็น empty array แล้ว บรรทัดนี้ไม่น่าจะจำเป็น ?

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationBox.tsx
> +        const messages = await response.json()
ย้ายไป service คับ

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationBox.tsx
> +    ])
ทำเป็น function ทำไมนะ ทำไมไม่ setMessages([ ...prevMessages, { new message } ]) ไปเลย

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationList.tsx
> +        const { name, lastMessage } = await response.json()
same ja, move to service

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationList.tsx
> +    lastMessage.length > 22 ? lastMessage.substring(0, 22) + "..." : lastMessage
ไม่ต้องแก้ก็ได้ แต่บอกเฉย ๆ ว่ามันมี css property text-overflow: ellipsis อยู่

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/ConversationList.tsx
> +        </p>
ถ้า case แก้สี text ให้ไปทางเดียวกันแบบนี้ ไป if else ใน className ของ div ก็ได้ จะได้ if else รอบเดียว btw แก้หรือไม่แก้ก็ได้ ไม่ซี

2024-02-10 16:34 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/components/Message.tsx
> +export default function Message({ message, sender, isRead, timeSent }: MessageInformation) {
'isRead' is defined but never used

2024-02-10 16:36 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/services/ConversationService.ts
อันนี้ของ file ConversationService.ts นะ comment แบบ file ละเหมือนมันจะมองไม่ชัด

2024-02-10 16:36 UTC, IamMrTeapot commented on frontend/src/pages/ConversationPage/services/ConversationService.ts
อันนี้ก็ของ file ConversationService.ts

2024-02-10 16:38 UTC, IamMrTeapot commented
แก้ Conflict ด้วยจ้า

2024-02-11 00:17 UTC, IamKittitat commented on backend/src/models/conversation/conversation.model.ts
> +}
เอ๊ะ ตอนแรกเข้าใจว่า ให้สร้างมาไว้สำหรับทุกอัน . แต่ลบละกัน

2024-02-11 00:19 UTC, IamKittitat commented on backend/src/repositories/conversation.repository.ts
> +          SELECT conversationid, created_at
คิดว่าแก้ไม่ทันละ รอแก้ใน PR หน้า โอเคปะ

2024-02-11 00:31 UTC, IamKittitat commented on frontend/src/pages/ConversationPage/components/ConversationList.tsx
> +    lastMessage.length > 22 ? lastMessage.substring(0, 22) + "..." : lastMessage
ขอเก็บไว้แบบเดิมละกัน ลองใช้ละ มันพังอยู่ดี
<img width="1440" alt="image" src="https://github.com/2110366-2566-2/MonDooDuang/assets/58716471/a3fb269c-5f53-49ee-939a-ce5afb968fd1">

2024-02-11 00:35 UTC, IamKittitat commented on frontend/src/pages/ConversationPage/components/ConversationList.tsx
> +        </p>
แก้ละกัน

2024-02-11 10:05 UTC, IamMrTeapot commented on backend/src/models/conversation/conversation.model.ts
> +}
คือมันควรใช้เป็น return type แหละ แต่ถ้ายังไม่ได้ใช้ช่างมันไปก่อนก็ได้

2024-02-11 10:11 UTC, IamMrTeapot approved these changes

2024-02-11 14:03 UTC, merged