[MD-88] Background and Navbar
2110366-2566-2/MonDooDuang pull request #13
Opened 2024-02-10 14:26 UTC by IamMrTeapot

**PR (Pull Request) Naming**
Please name the PR title as _"[MD-Number] Title"_

## What did you do in this PR ?
- Create RootLayout for background
- Create a Navigation bar
- Make the navigation bar able to handle most cases

2024-02-10 14:42 UTC, IamMrTeapot commented
<img width="947" alt="image" src="https://github.com/2110366-2566-2/MonDooDuang/assets/87607928/bc459df1-fe38-4641-a6f4-55677e917308">

2024-02-11 01:27 UTC, IamKittitat requested changes

2024-02-11 01:27 UTC, IamKittitat commented on frontend/src/common/components/NavBar/LogoutIcon.tsx
> +          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
file นี้คือ logo ชะ แต่ทำไมมันเยอะจังนะ เทียบกับ noti icon

2024-02-11 01:27 UTC, IamKittitat commented on frontend/src/common/components/NavBar/NavBar.tsx
> +type MenuFocus = "search" | "schedule" | "history" | "none"
แก้ history -> conversation ไหม  เพราะคลิกแล้วมันเข้า /conversation

2024-02-11 09:53 UTC, IamMrTeapot commented on frontend/src/common/components/NavBar/LogoutIcon.tsx
> +          <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
เป็น svg แบบกาว ๆ น่ะ มันชัดกว่า png นิดหน่อยเลยใช้

2024-02-11 09:54 UTC, IamMrTeapot commented on frontend/src/common/components/NavBar/NavBar.tsx
> +type MenuFocus = "search" | "schedule" | "history" | "none"
โอเค

2024-02-11 13:47 UTC, IamKittitat approved these changes

2024-02-11 13:47 UTC, merged