[MD-17, MD-18] Search Feature
2110366-2566-2/MonDooDuang pull request #16
Opened 2024-02-11 12:27 UTC by its144prelationship

**PR (Pull Request) Naming**
Please name the PR title as _"[MD-Number] Title"_

## What did you do in this PR ?
- FortunetellerModal which show Fortuneteller list after search
- SearchBar which consist of SearchBox, SpecialitySelector, PriceSelector, DateSelector, TimeSelector, RatingSelector
- Backend "/search" api
- Query search value from database

Note: Chat, Make appointment and Fortuneteller button in FortunetellerModal has not been connected yet.

2024-02-11 15:06 UTC, IamKittitat requested changes
- นี่กดระดับดาวแล้วมันไม่ทำงานอะ
- แนะนำว่าปรับพวก filter search cursor เป็น pointer ไหม

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx
> +import Star5Empty from "../Icons/star-5-empty-icon.svg"
มันใช้ซ้ำได้ไหม ทำไมต้องมี 5 files นะ

2024-02-11 15:06 UTC, IamKittitat commented on backend/src/routes/search.routes.ts
> +router.post("/", searchController.searchFortuneteller)
น่าจะต้อง get แทน post หรือเปล่า

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/SearchBox.tsx
> +}
ความจริงตรงนี้มันมีสองท่า คือถ้าจะใช้ interface อันนี้แค่ตรง props เอาออกเลยก็ได้ แต่เห็นว่าใช้หลายที่ละ ถ้าไม่อยากแก้ อย่างน้อยช่วยตั้งชื่อให้มันคล้ายๆ ไฟล์อื่นทีฮะ เช่น SearchBoxProps

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/RatingSelector.tsx
> +}
นี่ด้วยครับ แก้ชื่อไม่ก็เอาออก วิธีไหนก็ได้ ให้มันเหมือนกันทุกไฟล์

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/SpecialitySelector.tsx
> +
นี่ด้วยคับ

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchBar/SearchBar.tsx
> +interface Props {
ช่วยตั้งชื่อให้มัน consistency หน่อย

เช่น `frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx`

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/DateSelector.tsx
> +interface Props {
ช่วยตั้งชื่อให้มัน consistency หน่อย

เช่น `frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx`

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/SubmitButton.tsx
> +interface Props {
ช่วยตั้งชื่อให้มัน consistency หน่อย

เช่น `frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx`

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/DateSelectorOverlay.tsx
> +interface Props {
ช่วยตั้งชื่อให้มัน consistency หน่อย

เช่น frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx

2024-02-11 15:06 UTC, IamKittitat commented on backend/src/repositories/search.repository.ts
> +  search: async (searchOption: SearchSchema) => {
แก้ชื่อ function ให้มันสื่อความหมายกว่านี้ได้ไหม

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/DateSelectorOverlay.tsx
> +  ]
ไม่มีไร แค่สงสัยว่า คือใน DB เราเก็บเวลาเป็น UTC+0 นะ นี่อาจอ่านไม่เจอ แต่คือได้ handle หรือยังว่าเวลาที่เราใส่หรือหาเป็น UTC+0 ไม่ใช่ +7

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/DateSelectorOverlay.tsx
> +import { useState, useEffect, useRef } from "react"
ถ้าไม่ใช้ useRef เอาออกหน่อย

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchBar/SearchBar.tsx
> +import { useEffect } from "react"
ถ้าไม่ใช้ ลบ import ด้วย

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchBar/SearchBar.tsx
> +  searchFortuneTeller: any
ตรงพวก searchFortuneTeller ที่เป็น any สร้าง type มากำหนดมันได้ปะ

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/SpecialitySelector.tsx
> +  }, [])
มันไม่ consistency กับ file อื่นอะ เช่น `DateSelector`

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/components/SearchElements/TimeSelector.tsx
> +                      searchFortuneTeller.startHourTime < 10
พวก format ที่เอา 0 ไว้ข้างหน้า นี่มันทำตั้งแต่ข้างบนได้ไหมนะ แบบนี้มันค่อนข้างซ้ำซ้อน แล้วทำให้อ่านยากหรือเปล่า

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/services/SearchService.ts
> +        return dataMap.get("data")
ตรงนี้น่าปรับได้นะ เช่น
`
const data = await res.json()

return data["data"]
`

2024-02-11 15:06 UTC, IamKittitat commented on frontend/src/pages/SearchPage/services/SearchService.ts
> +        }
มี throw Error แต่ข้างนอกไม่มี handle

2024-02-11 15:06 UTC, IamKittitat commented on backend/src/repositories/search.repository.ts
> +                    SELECT * FROM FORTUNETELLER_PACKAGE`
ไม่มีไรแค่อยากคอมเม้นต์ว่านี่มันเกิดไรขึ้น ;-; เชื่อมั่นละกันว่าถูก ขอไม่เช็ค

2024-02-11 15:08 UTC, IamKittitat commented on backend/src/repositories/search.repository.ts
> +  search: async (searchOption: SearchSchema) => {
หมายถึง  line5

2024-02-11 15:18 UTC, its144prelationship commented on frontend/src/pages/SearchPage/components/Rating/RatingStar.tsx
> +import Star5Empty from "../Icons/star-5-empty-icon.svg"
องศา + สีดาวไม่เหมือนกัน🥲

2024-02-11 15:20 UTC, its144prelationship commented
> * นี่กดระดับดาวแล้วมันไม่ทำงานอะ
> * แนะนำว่าปรับพวก filter search cursor เป็น pointer ไหม

- คือข้อมูลใน db มันสลับ totalreview กับ totalscore พอเอามาเลยหารกันเป็น 0 หมดเลย
- อาเง

2024-02-11 15:21 UTC, its144prelationship commented on backend/src/routes/search.routes.ts
> +router.post("/", searchController.searchFortuneteller)
ควร get แบบใส่ body มากกว่าหรอ

2024-02-12 05:54 UTC, IamKittitat approved these changes

2024-02-12 06:36 UTC, merged