[MD-1] Registration: Fix number field validation
2110366-2566-2/MonDooDuang pull request #43
Opened 2024-03-12 08:36 UTC by matikant

**PR (Pull Request) Naming**
Please name the PR title as _"[MD-Number] Title"_

## What did you do in this PR ?
- add rules to validate number field
- phone number: number with 10 digits
- bank account number: number with 10-15 digits

2024-03-12 15:42 UTC, IamKittitat requested changes

2024-03-12 15:42 UTC, IamKittitat commented on frontend/src/pages/RegisterPage/RegisterPage.tsx
> +                  maxLength={120}
ไหนๆ คุณก็แก้มาละ ถ้าให้ตรงสไลด์ max = 100 เลย

2024-03-13 02:33 UTC, IamKittitat approved these changes

2024-03-13 17:28 UTC, matikant commented
- ย้ายทุกอย่างในนี้ไป branch ใหม่
- (น่าจะ) เพิ่ม check password constrain

2024-03-13 17:28 UTC, closed without merging