[MD-108] Navbar Admin
2110366-2566-2/MonDooDuang pull request #46
Opened 2024-03-12 14:13 UTC by Tinnaung

**PR (Pull Request) Naming**
Please name the PR title as _"[MD-Number] Title"_

## What did you do in this PR ?
- create navbar for admin
- modify authprovider for admin login
- fix bugs

2024-03-12 15:38 UTC, IamKittitat requested changes

2024-03-12 15:38 UTC, IamKittitat commented on frontend/src/pages/AppointmentPage/AppointmentPage.tsx
>    const { userId, userType, username } = useContext(AuthContext)
ตรงนี้เอาออกทำไมนะะ

2024-03-12 16:03 UTC, Tinnaung commented on frontend/src/pages/AppointmentPage/AppointmentPage.tsx
>    const { userId, userType, username } = useContext(AuthContext)
มันเอาไปใส่ใน Appointment panel แล้วอ่ะ

2024-03-13 03:49 UTC, IamKittitat approved these changes

2024-03-13 04:13 UTC, merged